version: "2"
linters:
  enable:
    - errorlint
    - goconst
    - gocritic
    - gosec
    - lll
    - misspell
    - mnd
    - nolintlint
    - paralleltest
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      disabled-checks:
        - ifElseChain
        - httpNoBody
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
    nolintlint:
      require-explanation: true
      require-specific: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/zarvd/iputil
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
